/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author ABHINESH
 */
public class Homepage{
    public JPanel AboutPanel = new JPanel();
//    Component AboutPanel;
    public Homepage(){
        
                AboutPanel.setLayout(new GridBagLayout());
                GridBagConstraints gc = new GridBagConstraints();
                Font fb= new Font("Arial",Font.BOLD,40);
                gc.insets= new Insets(5, 5, 5, 5);
                JLabel label1 = new JLabel("Text Manipulation Tools");
                Font f= new Font("Arial",Font.PLAIN,20);
                label1.setFont(fb);
                label1.setForeground(Color.BLACK);
                gc.gridy=0;
                gc.gridx=0;
                AboutPanel.add(label1,gc);
                JLabel label2 = new JLabel("Simple, single task, text manipulation tools." );
                label2.setFont(f);
                label2.setForeground(Color.BLACK);
                gc.gridy=1;
                gc.gridx=0;
                AboutPanel.add(label2,gc);
                JLabel label3 = new JLabel("Popular Tools" );
                label3.setFont(fb);
                gc.insets= new Insets(5, 5, 35, 5);
                label3.setForeground(Color.BLACK);
                gc.gridy=2;
                gc.gridx=0;
                AboutPanel.add(label3,gc);
                gc.insets= new Insets(5, 5, 5, 5);
                JLabel label4 = new JLabel("Add Prefix/Suffix in each Line." );
                label4.setFont(f);
                label4.setForeground(Color.BLACK);
                gc.gridy=3;
                gc.gridx=0;
                AboutPanel.add(label4,gc);
                JLabel label5 = new JLabel("Insert a prefix and/or suffix " );
                label5.setFont(f);
                label5.setForeground(Color.GRAY);
                gc.gridy=4;
                gc.gridx=0;
                AboutPanel.add(label5,gc);
                JLabel label6 = new JLabel("into the content of each line." );
                label6.setFont(f);
                label6.setForeground(Color.GRAY);
                gc.gridy=5;
                gc.gridx=0;
                AboutPanel.add(label6,gc);
                JLabel label7 = new JLabel("Add/Remove Line Breaks" );
                label7.setFont(f);
                label7.setForeground(Color.BLACK);
                gc.gridy=3;
                gc.gridx=1;
                AboutPanel.add(label7,gc);
                JLabel label8 = new JLabel("Add new line breaks " );
                label8.setFont(f);
                label8.setForeground(Color.GRAY);
                gc.gridy=4;
                gc.gridx=1;
                AboutPanel.add(label8,gc);
                JLabel label9 = new JLabel("and/or remove existing line breaks " );
                label9.setFont(f);
                label9.setForeground(Color.GRAY);
                gc.gridy=5;
                gc.gridx=1;
                AboutPanel.add(label9,gc);
                JLabel label10 = new JLabel("within your text's formatting." );
                label10.setFont(f);
                label10.setForeground(Color.GRAY);
                gc.gridy=6;
                gc.gridx=1;
                AboutPanel.add(label10,gc);
                gc.insets= new Insets(5, 65, 5, 5);
                JLabel label11 = new JLabel("Find and Replace Text" );
                label11.setFont(f);
                label11.setForeground(Color.BLACK);
                gc.gridy=3;
                gc.gridx=2;
                AboutPanel.add(label11,gc);
                //gc.insets= new Insets(5, 5, 5, 5);
                JLabel label12 = new JLabel("Find and replace text matching" );
                label12.setFont(f);
                label12.setForeground(Color.GRAY);
                gc.gridy=4;
                gc.gridx=2;
                AboutPanel.add(label12,gc);
                JLabel label13 = new JLabel(" your search criteria." );
                label13.setFont(f);
                label13.setForeground(Color.GRAY);
                gc.gridy=5;
                gc.gridx=2;
                AboutPanel.add(label13,gc);
                gc.insets= new Insets(35, 5, 5, 5);
                JLabel label14 = new JLabel("Remove Empty Lines" );
                label14.setFont(f);
                label14.setForeground(Color.BLACK);
                gc.gridy=7;
                gc.gridx=0;
                AboutPanel.add(label14,gc);
                gc.insets= new Insets(5, 5, 5, 5);
                JLabel label15 = new JLabel("Remove/delete all empty " );
                label15.setFont(f);
                label15.setForeground(Color.GRAY);
                gc.gridy=8;
                gc.gridx=0;
                AboutPanel.add(label15,gc);
                
                JLabel label16 = new JLabel("lines within your text/list." );
                label16.setFont(f);
                label16.setForeground(Color.GRAY);
                gc.gridy=9;
                gc.gridx=0;
                AboutPanel.add(label16,gc);
                gc.insets= new Insets(35, 5, 5, 5);
                JLabel label17 = new JLabel("Remove Extra Spaces" );
                label17.setFont(f);
                label17.setForeground(Color.BLACK);
                gc.gridy=7;
                gc.gridx=1;
                AboutPanel.add(label17,gc);
                gc.insets= new Insets(5, 5, 5, 5);
                JLabel label18 = new JLabel("Remove leading/trailing/extra/all" );
                label18.setFont(f);
                label18.setForeground(Color.GRAY);
                gc.gridy=8;
                gc.gridx=1;
                AboutPanel.add(label18,gc);
                JLabel label19 = new JLabel(" white-spaces from your text." );
                label19.setFont(f);
                label19.setForeground(Color.GRAY);
                gc.gridy=9;
                gc.gridx=1;
                AboutPanel.add(label19,gc);
                gc.insets= new Insets(35, 65, 5, 5);
                JLabel label20 = new JLabel("Remove Duplicate Lines" );
                label20.setFont(f);
                label20.setForeground(Color.BLACK);
                gc.gridy=7;
                gc.gridx=2;
                AboutPanel.add(label20,gc);
                gc.insets= new Insets(5, 65, 5, 5);
                JLabel label21 = new JLabel("Remove/delete all duplicate" );
                label21.setFont(f);
                label21.setForeground(Color.GRAY);
                gc.gridy=8;
                gc.gridx=2;
                AboutPanel.add(label21,gc);
                JLabel label22 = new JLabel(" lines within your text/list." );
                label22.setFont(f);
                label22.setForeground(Color.GRAY);
                gc.gridy=9;
                gc.gridx=2;
                AboutPanel.add(label22,gc);
                JLabel label23 = new JLabel("");
                label23.setFont(f);
                label23.setForeground(Color.BLACK);
                gc.gridy=11;
                gc.gridx=0;
                gc.ipady=130;
                AboutPanel.add(label23,gc);
                final JScrollPane scroll = new JScrollPane(AboutPanel);       
    }
}
